### ISSUE TITLE
adding user to repo

### ISSUE THREAD

**Issue by dimagimburg** [dimagimburg/mycvs#1]
had trouble adding user to repo that is substring of the username that is in repo now.

if the admin (user) that is connected with repo is "dimagimburg" the line in groups.db:

anotherRepo:dimagimburg

and i try to add user named "dima"

i get the error of already exists.

ill try to fix it later but i have to finish first the front end gui.

**Comment by vitalka200** [comment]
The match regex need to be changed to 
^pattern$ to make exact match.

**Comment by vitalka200** [comment]
fixed in commit #4bc5a6fde64e7ddf1b19e6de3a50bb3f3bfb92b8
